# Generated by Django 4.1.3 on 2022-11-20 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User_Restrictions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bank_id", models.PositiveIntegerField(verbose_name="Bank_id")),
                ("account_id", models.PositiveIntegerField(verbose_name="Account_id")),
                ("branch_id", models.PositiveIntegerField(verbose_name="Branch_id")),
                ("isrestricted", models.BooleanField(verbose_name="Is_Restricted")),
                ("expiration_date", models.DateField(verbose_name="Expiration_Date")),
            ],
        ),
    ]
