# Generated by Django 4.1.3 on 2022-11-20 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user_restrictions",
            name="expiration_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Expiration_Date"
            ),
        ),
    ]
